server:
  port: 8088

spring:
  application:
    name: profile-test
  profiles:
    active: dev
---
cn:
  itlz:
    a: test
spring:
  profiles: test

server:
  port: 8081
---
spring:
  profiles: dev

cn:
  itlz:
    a: dev-test