server:
  port: 8181
spring:
  application:
    name: rabc-test

  security:
    user:
      name: user
      password: user
      roles: test,haha

security:
  oauth2:
    client:
      client-id: itlz
      client-secret: itlz
      scope: all