server:
  port: 8001
security:
  oauth2:
    client:
      client-id: itlz
      client-secret: itlz
spring:
  security:
    user:
      name: user
      password: user

  redis:
    host: 192.168.88.134