server:
  port: 8000
spring:
  application:
    name: resource-server

  mvc:
    favicon:
      enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
  instance:
    hostname: localhost