spring:
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/bird99/config.git
          username: 77822013@qq.com
          password: 19951203d
          search-paths: /
  application:
    name: config-server

#  rabbitmq:
#    username: guest
#    password: guest
#    port: 5672
#    host: 192.168.88.137

server:
  port: 9000
management:
  endpoints:
    web:
      exposure:
        include: "*"